Repository grails/grails-testing-support, pull requests merged in 2021-12, with the labels that each got.

#164 Update chromeDriverVersion to 96.0.4664.45
  examples/demo33/gradle.properties
  examples/demo33/grails-app/conf/application.yml
Labels: type: dependency upgrade

#163 Java CI Workflow to use native gradle-build-action
  .github/workflows/gradle.yml
Labels: type: ci

#169 Remove clean from Java CI workflow
  .github/workflows/gradle.yml
Labels: type: ci

#170 Update release workflow to use gradle-build-action
  .github/workflows/release.yml
Labels: type: ci

#160 Fixed source paths to examples. (Changed from /apps/ to /examples/)
  src/main/docs/guide/unitTesting.adoc
  src/main/docs/guide/unitTesting/annotations.adoc
  src/main/docs/guide/unitTesting/unitTestingControllers.adoc
  src/main/docs/guide/unitTesting/unitTestingDomainClasses.adoc
  src/main/docs/guide/unitTesting/unitTestingInterceptors.adoc
  src/main/docs/guide/unitTesting/unitTestingServices.adoc
  src/main/docs/guide/unitTesting/unitTestingTagLibraries.adoc
  src/main/docs/guide/unitTesting/unitTestingUrlMappings.adoc
Labels: type: docs

#171 Enable Gradle Cache, Daemon, and Parallel
  gradle.properties
  settings.gradle
Labels: type: build

#175 Delete grailsApplication.mainContext.getBean("mimeTypesHolder") from …
  grails-testing-support/src/main/groovy/org/grails/testing/GrailsApplicationBuilder.groovy
  grails-web-testing-support/src/main/groovy/org/grails/testing/spock/WebSetupSpecInterceptor.groovy
Labels: type: improvement

#178 Define Gradle jvmArgs
  gradle.properties
Labels: type: build
