Repository grails/grails-testing-support, pull requests merged in 2024-09, with the labels that each got.

#412 update dependencies for grails 7
  build.gradle
  gradle.properties
Labels: maintenance, ci

#417 Move all versions numbers to gradle.properties and update dependencies
  build.gradle
  examples/demo33/build.gradle
  gradle.properties
Labels: maintenance, ci

#425 catch exception in GrailsApplicationBuilder
  grails-testing-support/src/main/groovy/org/grails/testing/GrailsApplicationBuilder.groovy
Labels: maintenance, build

#428 Fix #157 - Support @Before* and @After* methods; Restore ordering similar to JUnit 4/Spock ordering
  grails-testing-support/src/main/groovy/org/grails/testing/spock/TestingSupportExtension.groovy
  grails-testing-support/src/test/groovy/grails/testing/spock/JUnitAnnotationSpec.groovy
  grails-testing-support/src/test/groovy/grails/testing/spock/OnceBeforeSpec.groovy
Labels: bug

#430 Reapply "catch exception in GrailsApplicationBuilder (#425)"
  grails-testing-support/src/main/groovy/org/grails/testing/GrailsApplicationBuilder.groovy
Labels: maintenance, build

#436 Update groovy joint workflow, branch list, link to snapshot docs and update badges
  .github/workflows/groovy-joint-workflow.yml
  README.adoc
  build.gradle
  settings.gradle
Labels: documentation
